### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by mjavier2k** [mjavier2k/ping-identity-exporter#1]
- Create a Dockerfile to build a docker image for this exporter
- Update README on how to use the docker image

**Comment by hndoss** [comment]
Hi! I would like to help with this one.

**Comment by hndoss** [comment]
Weird. I see the label `hacktoberfest` but [this PR](https://github.com/mjavier2k/ping-identity-exporter/pull/2) is not being considered. Perhaps because this repository was created today.

**Comment by mjavier2k** [comment]
Thank you for working on this @hndoss !

I added a label hacktoberfest-accepted on your PR and should be considered now. Let me know though if it wasn't and I'll check why.

**Comment by hndoss** [comment]
All good! Thanks!
